import type { TeamId } from './team'

export type MatchId = string
/** Games in a series: any odd number (1 for a single game, 7 for NBA-style). */
export type BestOf = number

/** Which part of a stage a match belongs to. Used for layout, not logic. */
export type BracketSide = 'main' | 'upper' | 'lower' | 'grand-final' | 'third-place' | 'swiss'

/** Points at one of the two slots of a match. */
export interface SlotRef {
  matchId: MatchId
  slot: 0 | 1
}

export interface MatchSlot {
  /** null until the team is known (seeded, or fed in from an earlier match). */
  teamId: TeamId | null
  /** True when no team will ever fill this slot, so the other team gets a bye. */
  isBye?: boolean
  /**
   * While `teamId` is still null: a team already through to this match,
   * shown where it would play if every open match went to the better seed.
   * The real slot is set once the round before finishes (e.g. reseeding).
   */
  expected?: TeamId
}

/** 'bye' is generated by the engine when a team advances without playing. */
export type ResultSource = 'actual' | 'pick' | 'simulated' | 'bye'

/** Points, rounds or games won, keyed by team ID so it survives slot swaps. */
export type TeamScore = Record<TeamId, number>

/** One game within a series (a map in CS2, a game in the NFL). */
export interface GameResult {
  /** e.g. the map in CS2. */
  name?: string
  /**
   * Points (rounds, goals, ...) for each team. Whether a score is final
   * depends on the tournament's scoring rules.
   */
  score?: TeamScore
  /** With free scoring, marks a score as not final yet. */
  inProgress?: boolean
  /** For games without a decisive score, e.g. a forfeit or shootout. */
  winnerId?: TeamId
}

/**
 * Everything recorded for a match, from a single click (just `winnerId`)
 * to a full series with scores for every game. The winner comes from
 * `games` first, then `score`, then `winnerId`. A report without a winner
 * is a match in progress.
 */
export interface MatchReport {
  source: ResultSource
  winnerId?: TeamId
  /** Games won by each team. Derived from `games` when there are any. */
  score?: TeamScore
  games?: GameResult[]
}

/** A decided match. */
export interface MatchResult extends MatchReport {
  winnerId: TeamId
}

export interface Match {
  id: MatchId
  side: BracketSide
  /** 0-based round within its side. */
  round: number
  /** Display label, e.g. "Upper semi-final" or "2:1". */
  label?: string
  bestOf: BestOf
  slots: [MatchSlot, MatchSlot]
  /** What's been recorded, with anything that no longer fits these teams removed. */
  report?: MatchReport
  /** Set once the match is decided. */
  result?: MatchResult
  /** Where the winner advances. Absent for finals and Swiss matches. */
  winnerTo?: SlotRef
  /** Where the loser drops to. Absent when losing eliminates the team. */
  loserTo?: SlotRef
  scheduledAt?: string
}
